# test/pages/5_Glossary.py
import streamlit as st
import os
import sys
from config import app_config # To use APP_TITLE, etc. if needed in header or footer
import logging

# --- Explicitly add project root to sys.path for robust imports ---
# PROJECT_ROOT_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
# if PROJECT_ROOT_PATH not in sys.path:
#     sys.path.insert(0, PROJECT_ROOT_PATH)
# NOTE: For a page directly in `pages/`, this sys.path manipulation
#       for finding `config` and `utils` is generally not needed if
#       `app_home.py`'s directory is added to sys.path by Streamlit.
#       However, if you keep it, ensure `os.pardir` points to the correct project root.
#       For a file in `test/pages/`, `os.pardir` goes to `test/`.

# Simplified path addition for pages - assuming main script in 'test' is on path
module_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..')) # this should give 'test'
if module_path not in sys.path:
    sys.path.append(module_path)


# --- Page Configuration ---
st.set_page_config(
    page_title="Glossary - Health Hub",
    layout="wide",
    initial_sidebar_state="expanded" 
    # page_icon can be inherited or set specifically
)

logger = logging.getLogger(__name__)

# --- Load CSS (Optional - if you want consistent styling) ---
@st.cache_resource # Using cache_resource for functions that load resources
def load_css_glossary():
    css_path = app_config.STYLE_CSS_PATH # Uses app_config, so config import must work
    if os.path.exists(css_path):
        with open(css_path) as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
            logger.info("Glossary Page: CSS loaded.")
    else:
        logger.warning(f"Glossary Page: CSS file not found at {css_path}.")
load_css_glossary()

# --- Glossary Content ---
st.title("📜 Glossary of Terms and Abbreviations")
st.markdown("This page provides definitions for common terms, abbreviations, and metrics used throughout the Health Intelligence Hub.")
st.markdown("---")

# Helper function for consistent formatting (optional)
def display_term(term, definition):
    st.markdown(f"**{term}**")
    st.markdown(f": {definition}")
    st.markdown("---") # Add a small separator

# You can organize by category using st.subheader()
st.header("🩺 Clinical & Epidemiological Terms")

display_term("AI Risk Score", "An algorithmic score (0-100) predicting a patient's general health risk or likelihood of adverse outcomes. Higher scores indicate higher risk.")
display_term("AI Follow-up Priority Score", "A score (0-100) generated by an AI model to help prioritize which patients require more urgent follow-up based on a combination of factors.")
display_term("ART", "Antiretroviral Therapy – medication used to treat HIV infection.")
display_term("AFB (Sputum-AFB)", "Acid-Fast Bacilli. A type of bacteria that includes Mycobacterium tuberculosis, the cause of TB. Sputum-AFB test looks for these bacteria in a phlegm sample.")
display_term("Case Detection Rate (CDR)", "The proportion of estimated new tuberculosis (TB) cases diagnosed and officially reported in a given year.")
display_term("Comorbidity", "The simultaneous presence of two or more diseases or medical conditions in a patient.")
display_term("CFR (Case Fatality Rate)", "The proportion of individuals diagnosed with a specific disease who die from that disease within a certain period.")
display_term("CHW", "Community Health Worker – a frontline public health worker who is a trusted member of and/or has an  unusually close understanding of the community served.")
display_term("Contact Tracing", "The process of identifying, assessing, and managing people who have been exposed to a disease to prevent onward transmission.")
display_term("DHO", "District Health Officer – a public health official responsible for managing and overseeing health services and programs at the district level.")
display_term("DOTS", "Directly Observed Treatment, Short-course – a strategy for TB control where a health worker or trained volunteer observes the patient swallowing their TB medications.")
display_term("Encounter", "Any interaction a patient has with the health system (e.g., clinic visit, CHW home visit, teleconsultation).")
display_term("GeneXpert (Sputum-GeneXpert)", "A molecular test for TB that can also detect resistance to rifampicin, a key TB drug.")
display_term("HbA1c", "Glycated Hemoglobin – a blood test that reflects average blood sugar levels over the past 2-3 months, used for diagnosing and monitoring diabetes.")
display_term("HIV", "Human Immunodeficiency Virus – a virus that attacks the body's immune system.")
display_term("HPV", "Human Papillomavirus – a common virus that can cause warts and some types of cancer, including cervical cancer.")
display_term("Incidence", "The rate of new cases of a disease occurring in a population over a specific period.")
display_term("KPI", "Key Performance Indicator – a measurable value that demonstrates how effectively a system or activity is achieving key objectives.")
display_term("Linkage to Care", "The process of ensuring that patients diagnosed with a condition (e.g., HIV, TB) are successfully enrolled in appropriate treatment and care services.")
display_term("Malaria RDT", "Malaria Rapid Diagnostic Test – a quick test to detect malaria antigens in a person's blood.")
display_term("NAAT-GC", "Nucleic Acid Amplification Test for Gonorrhea (GC) – a sensitive lab test to detect Neisseria gonorrhoeae.")
display_term("Positivity Rate (Test)", "The percentage of all tests conducted for a specific disease that yield a positive result.")
display_term("Prevalence", "The total number of cases of a disease existing in a population at a specific point in time or over a period.")
display_term("RPR (Rapid Plasma Reagin)", "A blood test for syphilis.")
display_term("SDOH (Social Determinants of Health)", "The non-medical factors that influence health outcomes. They are the conditions in which people are born, grow, work, live, and age, and the wider set of forces and systems shaping the conditions of daily life.")
display_term("SES", "Socio-Economic Status – a measure of an individual's or family's economic and social position in relation to others, based on income, education, and occupation.")
display_term("SpO2", "Peripheral Capillary Oxygen Saturation – an estimate of the amount of oxygen in the blood, measured using a pulse oximeter.")
display_term("STI", "Sexually Transmitted Infection.")
display_term("Syndromic Surveillance", "Monitoring based on health-related data that precede diagnosis and signal a sufficient probability of a case or an outbreak to warrant further public health response (e.g., tracking clusters of symptoms).")
display_term("TAT (Test Turnaround Time)", "The time elapsed from when a sample is collected or received by the lab to when the result is available/reported.")
display_term("TB", "Tuberculosis – an infectious disease usually caused by Mycobacterium tuberculosis (MTB) bacteria, generally affecting the lungs.")
display_term("Viral Load (HIV)", "The amount of HIV in a sample of blood. Used to monitor the effectiveness of ART.")

st.header("💻 Technical & Platform Terms")
display_term("CSV", "Comma-Separated Values – a simple file format used to store tabular data (numbers and text) in plain text.")
display_term("GeoJSON", "An open standard format designed for representing simple geographical features along with their non-spatial attributes.")
display_term("GDF (GeoDataFrame)", "A data structure from the GeoPandas library, similar to a Pandas DataFrame but with added geospatial capabilities (e.g., storing geometries).")
display_term("IoT", "Internet of Things – a network of physical objects ('things') that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the internet.")
display_term("PPM (Parts Per Million)", "A unit of concentration, often used for CO2 levels.")
display_term("µg/m³ (Micrograms per cubic meter)", "A unit of concentration for particulate matter like PM2.5.")
display_term("PM2.5", "Fine inhalable particles, with diameters that are generally 2.5 micrometers and smaller. A common air quality indicator.")
display_term("VOC (Volatile Organic Compound)", "Organic chemicals that have a high vapor pressure at ordinary room temperature. Some can be harmful. VOC Index is a measure of their concentration.")

# ... (Add more terms and categories as the platform evolves) ...

st.markdown("---")
st.caption(app_config.APP_FOOTER)
